Update nl.tts
asamm/locus-map-tts-commands pull request #1
Opened 2020-01-05 20:57 UTC by tycho366

2020-02-07 17:44 UTC, menion requested changes

2020-02-07 17:44 UTC, menion commented on src/main/assets/tts_commands/nl.tts
> +		"poi_alert_point_X": "Punt %S ligt op %D2 op %N5 uur",
This is an incorrect definition. You try to use number formating `%N5` , but it is not defined as a `numbers_N5` in the file.

2020-02-10 17:45 UTC, tycho366 commented on src/main/assets/tts_commands/nl.tts
> +		"poi_alert_point_X": "Punt %S ligt op %D2 op %N5 uur",
I fixed the format error and committed the change.

2020-03-25 06:27 UTC, merged

2020-03-25 06:28 UTC, menion commented
Thanks tycho and sorry for the delay. PR merged. Changes will be in the next 3.45 version (or any beta if it comes sooner).